### ISSUE TITLE
Geometry support (part 2)

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform-View#4]
Remaining:

- [x] SkinnedMesh
- [ ] triangle fan
- [ ] triangle strip

**Comment by DennisSmolek** [comment]
Hmm so a rigged character would likely not load?

**Comment by donmccurdy** [comment]
Currently it'll load as a static mesh in default pose. Might have a scaling difference if the skeleton had transforms on it.

**Comment by donmccurdy** [comment]
Moving this package into the https://github.com/donmccurdy/glTF-Transform monorepo.
