### ISSUE TITLE
Extension support

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform-View#7]
**P0:**

- [x] KHR_draco_mesh_compression
- [x] KHR_mesh_quantization
- [x] KHR_materials_clearcoat
- [x] KHR_materials_ior
- [x] KHR_materials_sheen
- [x] KHR_materials_specular
- [x] KHR_materials_transmission
- [x] KHR_materials_volume
- [x] KHR_materials_unlit
- [x] KHR_texture_basisu
- [x] KHR_texture_transform
- [x] EXT_meshopt_compression
- [x] EXT_texture_webp

**P1:**

- [x] KHR_lights_punctual
- [x] KHR_materials_emissive_strength

**P2:**

- [x] KHR_materials_iridescence
- [ ] KHR_materials_variants
- [x] EXT_mesh_gpu_instancing

**Out of scope:**

- [ ] ~~KHR_materials_pbrSpecularGlossiness~~

**Comment by DennisSmolek** [comment]
Curious why no lights? Seems that’s on by default in three

**Comment by donmccurdy** [comment]
No obstacle, just not implemented yet -- note that this project is not using GLTFLoader so these pieces have to be rewritten.

**Comment by donmccurdy** [comment]
PR for light support:

- https://github.com/donmccurdy/glTF-Transform-View/pull/43

**Comment by donmccurdy** [comment]
Added in #64:

- KHR_materials_emissive_strength
- KHR_materials_iridescence

**Comment by donmccurdy** [comment]
Moving this package into the https://github.com/donmccurdy/glTF-Transform monorepo.
